enableTelemetry: false

enableTimers: true

logFilters:
  - code: YN0076
    level: discard

nodeLinker: node-modules

packageExtensions:
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependenciesMeta:
      typescript:
        optional: true
  '@firebase/analytics-compat@^0.1.0':
    peerDependenciesMeta:
      '@firebase/app':
        optional: true
      '@firebase/app-types':
        optional: true
  '@firebase/app-check-compat@^0.2.0':
    peerDependenciesMeta:
      '@firebase/app':
        optional: true
      '@firebase/app-types':
        optional: true
  '@firebase/auth-compat@^0.2.0':
    peerDependenciesMeta:
      '@firebase/app':
        optional: true
      '@firebase/app-types':
        optional: true
  '@firebase/database@^0.12.0':
    peerDependenciesMeta:
      '@firebase/app':
        optional: true
      '@firebase/app-types':
        optional: true
  '@firebase/firestore-compat@^0.1.0':
    peerDependenciesMeta:
      '@firebase/app':
        optional: true
      '@firebase/app-types':
        optional: true
  '@firebase/functions-compat@^0.1.0':
    peerDependenciesMeta:
      '@firebase/app':
        optional: true
      '@firebase/app-types':
        optional: true
  '@firebase/functions@^0.7.0':
    peerDependenciesMeta:
      '@firebase/app':
        optional: true
      '@firebase/app-types':
        optional: true
  '@firebase/messaging-compat@^0.1.0':
    peerDependenciesMeta:
      '@firebase/app':
        optional: true
      '@firebase/app-types':
        optional: true
  '@firebase/performance-compat@^0.1.0':
    peerDependenciesMeta:
      '@firebase/app':
        optional: true
      '@firebase/app-types':
        optional: true
  '@firebase/remote-config-compat@^0.1.0':
    peerDependenciesMeta:
      '@firebase/app':
        optional: true
      '@firebase/app-types':
        optional: true
  '@firebase/storage-compat@^0.1.0':
    peerDependenciesMeta:
      '@firebase/app':
        optional: true
      '@firebase/app-types':
        optional: true
  '@mdx-js/loader@^1.6.0':
    peerDependenciesMeta:
      react:
        optional: true
  '@storybook/addon-essentials@^6.3.0':
    peerDependenciesMeta:
      '@storybook/components':
        optional: true
      '@storybook/core-events':
        optional: true
      '@storybook/theming':
        optional: true
  '@storybook/addon-postcss@^2.0.0':
    peerDependenciesMeta:
      webpack:
        optional: true
  '@storybook/core@^6.3.0':
    peerDependenciesMeta:
      webpack:
        optional: true
  '@storybook/csf-tools@^6.3.0':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
  emoji-mart-virtualized@^3.1.0:
    peerDependenciesMeta:
      react-dom:
        optional: true
  razzle@^4.2.0:
    peerDependenciesMeta:
      '@babel/core':
        optional: true
  react-dev-utils@^11.0.0:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  react-hot-toast@^2.1.0:
    peerDependenciesMeta:
      csstype:
        optional: true
  react-use-web-share@^1.0.0:
    peerDependenciesMeta:
      react-dom:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-echo-execute.cjs
    spec: 'https://yarnplugins.com/echo-execute'
